### PR TITLE
Get 4 menu items from resourceBundle.

### PR DESCRIPTION
**Pull request by wonsiks**
Menu.game.scoreGame
Menu.analyze.rule
Menu.help
Menu.help.keyboardControls

### CODE REVIEW

**Comment by hope366** [comment]
I manage Lizzie-improvements, but I know very little about programming.
Can you tell me what these three pull requests mean?

**Comment by wonsiks** [comment]
@hope366
Current source code : Display names are hard coded in the source file(Menu.java)
Changed code : Real display names are defined in resource files and call them from source file so that the menus can be written in various languages.(English, Japanese, Korean, ...)
I've just changed English and Korean language file and you can change Japanese by editing DisplayStrings_ja.properties file.

**Comment by hope366** [comment]
I see, that's a convenient mechanism ^^
I would like to change DisplayStrings_ja_JP.Properties,
Where can I find something like "u30c9"?

**Comment by wonsiks** [comment]
@hope366 .properties file uses unicode. So you need to convert Japanese language to unicode.
You can convert your string from https://www.online-toolz.com/tools/text-unicode-entities-convertor.php
After you get unicode then need to change % into \ then write it into .properties file.

**Comment by hope366** [comment]
Thank you for providing us with valuable information.
I modified DisplayStrings_ja_JP.properties and compiled it.
Apparently it worked ^^

**Comment by wonsiks** [comment]
@hope366 Cool...
What about changing 'Clear analysis' too?

**Comment by hope366** [comment]
Menu.java line 1293
  `new JMenuItem (resourceBundle.getString ("Menu.analyze.clearAnalysis "));`
Since it is already like this, should I just change DisplayStrings_ja_JP.properties?

**Comment by wonsiks** [comment]
@hope366 Yes, just changing .properties file then it will work.

**Comment by hope366** [comment]
Now all the display items are in Japanese ^^
Great!

**Comment by wonsiks** [comment]
@hope366 It's great!!! Congratulations...

**Comment by hope366** [comment]
I've always wanted to know about Unicode. I am very happy to be able to do something new today.
thank you very much.

**Comment by wonsiks** [comment]
@hope366 I'm happy to help you too...:)

**Pull request merged**
